version: '3'
services:
    ebooks:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
        - "5001:5001"
    redis:
        command: sh -c 'redis-server --bind 0.0.0.0'
        restart: always